### ISSUE TITLE
Execute on all new revisions failed

### ISSUE THREAD

**Issue by yiikou** [smartshark/coastSHARK#3]
I tried coastSHARK via serverSHAR. After collecting vcs data, I start the coastSHARK and got this error for all subjobs:
```
executing: /srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.4/execute.sh a6242f25f4dc624c3c930f67d397bddb14577863 /tmp/servershark/projects/grimoirelab-perceval /srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.4 https://github.com/chaoss/grimoirelab-perceval.git grimoirelab-perceval root CHANGEME smartshark localhost 27017 smartshark None None None  ... finished in 0.56592s [ERROR]
Traceback (most recent call last):
  File "/srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.4/smartshark_plugin.py", line 112, in <module>
    main(parser.parse_args())
  File "/srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.4/smartshark_plugin.py", line 44, in main
    raise Exception('--input needs trailing slash')
Exception: --input needs trailing slash
```

And I tried just execute with on revision, and add the slash as finish. e.g., `39e220d2cc0d1125471917756b3cbb95da0feb3e/`. Then I got this: `    error: pathspec '39e220d2cc0d1125471917756b3cbb95da0feb3e/' did not match any file(s) known to git.
error checkout`.

How should I properly use this plugin in serverSHARK?

Thank you.

**Comment by atrautsch** [comment]
That is strange, the execute.sh should automatically append a slash. The / should be appended on the input path, e.g., -i /tmp/project/ instead of only /tmp/project
That being said, there is no reason not to fix that automatically in smartshark_plugin.py. I will create an update.

**Comment by yiikou** [comment]
Thanks, looking forward to that, and if I use the earlier version, will that works?

Also, I wonder that where can I find the visualization in visualSHARK for these plugin? For example, I tried mecoSHARK and linkSHARK, they seem work (since no error). Then I update the project and project attribute, but didn't find corresponding information. For example, mecoSHARK should provide dozens new metrics.

Thank you.

**Comment by atrautsch** [comment]
MecoSHARK and coastSHARK metrics should be visible in the commit view, below FileActions there should be CodeEntityStates which contain the metrics.

**Comment by yiikou** [comment]
I see. That section is still empty. I assume it means 1) data not synced. 2) plugin execute failed? To make sure data is synced up, do I just execute `python manage.py create_project_stats`?

**Comment by atrautsch** [comment]
No, that should be instant as they are fetched directly from the MongoDB. The stats is only needed because of expensive calculations regarding some counts per project. Were there Java files changed in the commit? It would be empty if only non code files were changed in that commit.

**Comment by yiikou** [comment]
My selected project is a python project. Is it suggested to test on java project instead?

**Comment by atrautsch** [comment]
CoastSHARK should work for either although I would recommend Java to see if everything works.
Btw. new version of coastSHARK is available I hope that it works now.
If you use the fetch from Github in ServerSHARK it should work directly, you can then deactivate the old coastSHARK plugin in the plugins view.

**Comment by yiikou** [comment]
Thanks for the quick response! I deactived, and try to install the 2.05 version. It shows `Assets not found`.

Btw, where can I check the visualization result from linkSHARK?

----
Update: I tried to install manually by uploading archive (in .zip and .tar.gz), while both formats are not suppported.

**Comment by atrautsch** [comment]
OK, then I would have to take a look tomorrow and run the new version on a local serverSHARK instance.
The linkSHARK results should be visible in the commit view, there is an analytics box where it should list the issue links under issue links. However, if you want to work with the data be sure to take a look at our usage_examples repository. It has jupyter notebooks which access the MongoDB data directly.

The manual install with upload is meant for local development, it requires a plain tar format that is created by the build_plugin.sh script in plugin_packaging.

**Comment by yiikou** [comment]
ah I see. thank you! I will try to create a local plugin first.

**Comment by atrautsch** [comment]
The upload option is basically the same as the github install it has the advantage that we do not need to create a new release when developing plugins and testing with serverSHARK.

**Comment by yiikou** [comment]
I compressed one and installed successfully. But now there is new situation....
```
invalid syntax (test_backend.py, line 58)
Traceback (most recent call last):
  File "/srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.5/smartshark_plugin.py", line 77, in main
    e.load()
  File "/srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.5/util/extract_ast.py", line 199, in load
    self.astdata = ast.parse(source=convert_2to3(f.read() + '\n', self.filename), filename=self.filename)
  File "/usr/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "/dev/shm/BDXKqMc8T5C8WMDbhntdoJSCNiqP2qx4/tests/test_backend.py", line 58
    from . import mocked_package.nested_package
                                ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.5/smartshark_plugin.py", line 116, in <module>
    main(parser.parse_args())
  File "/srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.5/smartshark_plugin.py", line 77, in main
    e.load()
  File "/srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.5/util/extract_ast.py", line 199, in load
    self.astdata = ast.parse(source=convert_2to3(f.read() + '\n', self.filename), filename=self.filename)
  File "/usr/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "/dev/shm/BDXKqMc8T5C8WMDbhntdoJSCNiqP2qx4/tests/test_backend.py", line 58
    from . import mocked_package.nested_package
                                ^
SyntaxError: invalid syntax
```

Is it due to lacking of some required pkgs?

**Comment by atrautsch** [comment]
It seems that it is a problem of the target project or that it uses Python syntax of a newer Python version.
CoastSHARK uses builtin Python functions wherever possible, this has the limitation that if the parsing fails due to syntax errors it will not work. That includes new syntax due to new Python features, e.g., if the project is written for Python 3.7 and coastSHARK is run with Python 3.6.
I could simply log the error and carry on regardless so that it would work for the rest of the files.

**Comment by atrautsch** [comment]
> Thanks for the quick response! I deactived, and try to install the 2.05 version. It shows `Assets not found`.
I cannot reproduce this, I created a clean serverSHARK VM with Vagrant and installed vcsSHARK and coastSHARK and ran coastSHARK after vcsSHARK. I used a Java project and it did work out of the box.
