### ISSUE TITLE
CoastSHARK installation seems problematic

### ISSUE THREAD

**Issue by yiikou** [smartshark/coastSHARK#4]
I installed the plugin using serverSHARK, (in sudo -i and venv mode).

The direct observation is the failure when executing the plugin:
```
executing: /srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.5/execute.sh 7c2f12c92bd5c66f4cac65dfdf86863c665a13ec /tmp/servershark/projects/junit4 /srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.5 https://github.com/junit-team/junit4.git junit4 root CHANGEME smartshark localhost 27017 smartshark None None None  ... finished in 0.42416s [ERROR]
Traceback (most recent call last):
  File "/srv/www/serverSHARK/plugin_installations/coastSHARK_2.0.5/smartshark_plugin.py", line 11, in <module>
    from util import error
ImportError: cannot import name 'error'
```

When I test coastSHARK by executing `python setup.py test`, I got:
```
ERROR: coastSHARK (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: coastSHARK
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'coastSHARK'
```
Even after a small fix on the `setup.py` (change 2.0.4 to 2.0.5). the problem still exists.

My assumptions:
1) the installation is under python 2, hence then setup.py install failed. But the plugin installation is executed by the worker, and the work is running under "sudo -i" and python venv (according to serverSHARK).
2) The build process needs to be double checked.

Thank you.

**Comment by yiikou** [comment]
After reset vagrant environment and delete all data, coastSHARK works...

**Comment by yiikou** [comment]
The problem occurs again. And it seems the clean installation is ok (first install vsc and then coast, it works well). While after install other plugins, the installation of other plugins change somethings (system environment?), and make the plugin cannot run anymore.

Currently, I have to re deploy a new vagrant, and first finish any necessary analysis related with coastSHARK. Then install other plugins.

====
After hours trying...I found it is the installation of inducingSHARK messing up the environment.

**Comment by atrautsch** [comment]
Did you use the upload to install coastSHARK?
I used the Github install two days ago with this version and it worked fine.
If you install the plugin via serverSHARK the installation is executed by the worker which also does the execution there should not be a problem with python2.

I will try to reproduce the problem with the inducingSHARK.

**Comment by atrautsch** [comment]
I cannot reproduce this, I have coastSHARK installed and after I install inducingSHARK it stil works. Maybe you can try the updated inducingSHARK (1.1.0). However there should be nothing in the changes responsible for plugin environment mixups.
I am pushing a new coastSHARK version, it seems a init is missing maybe this fixes your problem. It also corrects the version in the setup.py.

**Comment by yiikou** [comment]
Thanks for the suggestion. After re-install coastSHARK, and use inducingSHARK 1.1.0, the problem solved.
